include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - lib/generated/**

linter:
  rules:
    # Performance Improvements
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_redundant_argument_values: true
    prefer_final_locals: true
    prefer_final_fields: true
    unnecessary_this: true

    # Important Warnings & Best Practices
    avoid_dynamic_calls: true
    prefer_const_declarations: true
    always_declare_return_types: true
    # Avoid Using print
    avoid_print: true